name: Cleanup (cron)
on:
  schedule:
    - cron: '30 10 * * SUN' # every sunday at 10:30

permissions:
  contents: read
  actions: write

jobs:
  deleteArtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: kolpav/purge-artifacts-action@04c636a505f26ebc82f8d070b202fb87ff572b10 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 21 days
  cleanupCloudRunner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        if: github.event.event_type != 'pull_request_target'
        with:
          lfs: true
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '18'
      - run: yarn
      - run: yarn run cli --help
        env:
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
      - run: yarn run cli -m list-resources
        env:
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
